"""empty message

Revision ID: 215a222a6d1a
Revises: 
Create Date: 2018-01-19 10:11:16.537671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215a222a6d1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('azs_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('azstype', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('divisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dzo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('service', sa.String(length=60), nullable=True),
    sa.Column('manager', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geo', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('isp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('phones', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('manager', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=True),
    sa.Column('quality', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('region_mgmt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ru',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('geo', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=False)
    op.create_table('zip_addr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=15), nullable=True),
    sa.Column('address', sa.String(length=30), nullable=True),
    sa.Column('manager', sa.String(length=30), nullable=True),
    sa.Column('contact', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zip_addr_address'), 'zip_addr', ['address'], unique=False)
    op.create_index(op.f('ix_zip_addr_city'), 'zip_addr', ['city'], unique=False)
    op.create_index(op.f('ix_zip_addr_contact'), 'zip_addr', ['contact'], unique=False)
    op.create_index(op.f('ix_zip_addr_manager'), 'zip_addr', ['manager'], unique=False)
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main_ex', sa.Boolean(), nullable=True),
    sa.Column('main_isp', sa.Integer(), nullable=True),
    sa.Column('main_type', sa.Integer(), nullable=True),
    sa.Column('main_net', sa.String(length=10), nullable=True),
    sa.Column('main_gre', sa.String(length=10), nullable=True),
    sa.Column('back_ex', sa.Boolean(), nullable=True),
    sa.Column('back_isp', sa.Integer(), nullable=True),
    sa.Column('back_type', sa.Integer(), nullable=True),
    sa.Column('back_net', sa.String(length=10), nullable=True),
    sa.Column('back_gre', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['back_isp'], ['isp.id'], ),
    sa.ForeignKeyConstraint(['back_type'], ['media.id'], ),
    sa.ForeignKeyConstraint(['main_isp'], ['isp.id'], ),
    sa.ForeignKeyConstraint(['main_type'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('division', sa.Integer(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['division'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['rank'], ['rank.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('azs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sixdign', sa.Integer(), nullable=True),
    sa.Column('ru', sa.Integer(), nullable=True),
    sa.Column('region_mgmt', sa.Integer(), nullable=True),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.Column('hostname', sa.String(length=30), nullable=True),
    sa.Column('dzo', sa.Integer(), nullable=True),
    sa.Column('azs_type', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('data_added', sa.DateTime(), nullable=True),
    sa.Column('user_added', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['azs_type'], ['azs_type.id'], ),
    sa.ForeignKeyConstraint(['dzo'], ['dzo.id'], ),
    sa.ForeignKeyConstraint(['region_mgmt'], ['region_mgmt.id'], ),
    sa.ForeignKeyConstraint(['ru'], ['ru.id'], ),
    sa.ForeignKeyConstraint(['user_added'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('num')
    )
    op.create_index(op.f('ix_azs_sixdign'), 'azs', ['sixdign'], unique=True)
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_timestamp'), 'comment', ['timestamp'], unique=False)
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('prereason', sa.String(length=30), nullable=True),
    sa.Column('pretimestamp', sa.DateTime(), nullable=True),
    sa.Column('azs_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['azs_id'], ['azs.id'], ),
    sa.ForeignKeyConstraint(['reason'], ['reasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hardware',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gate_vend', sa.Integer(), nullable=True),
    sa.Column('gate_vers', sa.String(length=10), nullable=True),
    sa.Column('gate_serial', sa.String(length=10), nullable=True),
    sa.Column('gate_lic', sa.String(length=10), nullable=True),
    sa.Column('gate_owner', sa.Integer(), nullable=True),
    sa.Column('gate_install', sa.DateTime(), nullable=True),
    sa.Column('gate_zip', sa.Integer(), nullable=True),
    sa.Column('router_vend', sa.Integer(), nullable=True),
    sa.Column('router_vers', sa.String(length=10), nullable=True),
    sa.Column('router_serial', sa.String(length=10), nullable=True),
    sa.Column('router_lic', sa.String(length=10), nullable=True),
    sa.Column('router_owner', sa.Integer(), nullable=True),
    sa.Column('router_install', sa.DateTime(), nullable=True),
    sa.Column('router_zip', sa.Integer(), nullable=True),
    sa.Column('azs_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['azs_id'], ['azs.id'], ),
    sa.ForeignKeyConstraint(['gate_owner'], ['dzo.id'], ),
    sa.ForeignKeyConstraint(['gate_vend'], ['vendors.id'], ),
    sa.ForeignKeyConstraint(['gate_zip'], ['zip_addr.id'], ),
    sa.ForeignKeyConstraint(['router_owner'], ['dzo.id'], ),
    sa.ForeignKeyConstraint(['router_vend'], ['vendors.id'], ),
    sa.ForeignKeyConstraint(['router_zip'], ['zip_addr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mss_net', sa.String(length=10), nullable=True),
    sa.Column('kspd_all', sa.String(length=10), nullable=True),
    sa.Column('s_arm', sa.String(length=10), nullable=True),
    sa.Column('s_su', sa.String(length=10), nullable=True),
    sa.Column('s_tel', sa.String(length=10), nullable=True),
    sa.Column('s_tv', sa.String(length=10), nullable=True),
    sa.Column('s_video', sa.String(length=10), nullable=True),
    sa.Column('s_kontar', sa.String(length=10), nullable=True),
    sa.Column('s_interkom', sa.String(length=10), nullable=True),
    sa.Column('x_coffe', sa.String(length=10), nullable=True),
    sa.Column('x_kkm', sa.String(length=10), nullable=True),
    sa.Column('x_term', sa.String(length=10), nullable=True),
    sa.Column('x_safe', sa.String(length=10), nullable=True),
    sa.Column('azs_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['azs_id'], ['azs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('reason', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('prereason', sa.String(length=30), nullable=True),
    sa.Column('pretimestamp', sa.DateTime(), nullable=True),
    sa.Column('azs_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['azs_id'], ['azs.id'], ),
    sa.ForeignKeyConstraint(['reason'], ['reasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status')
    op.drop_table('ip')
    op.drop_table('hardware')
    op.drop_table('address')
    op.drop_index(op.f('ix_comment_timestamp'), table_name='comment')
    op.drop_table('comment')
    op.drop_index(op.f('ix_azs_sixdign'), table_name='azs')
    op.drop_table('azs')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('channels')
    op.drop_index(op.f('ix_zip_addr_manager'), table_name='zip_addr')
    op.drop_index(op.f('ix_zip_addr_contact'), table_name='zip_addr')
    op.drop_index(op.f('ix_zip_addr_city'), table_name='zip_addr')
    op.drop_index(op.f('ix_zip_addr_address'), table_name='zip_addr')
    op.drop_table('zip_addr')
    op.drop_index(op.f('ix_vendors_name'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_table('ru')
    op.drop_table('region_mgmt')
    op.drop_table('reasons')
    op.drop_table('rank')
    op.drop_table('media')
    op.drop_table('isp')
    op.drop_table('geo')
    op.drop_table('dzo')
    op.drop_table('divisions')
    op.drop_table('azs_type')
    # ### end Alembic commands ###
